"use client";
import Head from "next/head";
import { Container, ThemeProvider } from "@mui/material";
import ShareListLoader from "@/components/ShareListLoader";
import ListView from "@/components/ListView";
import { theme } from "@/theme";
import MultiplierSelector from "@/components/MultiplierSelector";

export default function Home() {
  return (
    <>
      <Head>
        <title>OPR GFF/AoFS - Beefy Mode</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Container sx={{ pt: 2 }}>
          <ShareListLoader />
          <MultiplierSelector />
          <ListView />
        </Container>
      </ThemeProvider>
    </>
  );
}
